backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "assets/images"

slug:
  encoding: "unicode"
  clean_accents: false


collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Publicación" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Contenido", name: "body", widget: "markdown"}

